FROM node:20-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

RUN apk add --no-cache libc6-compat

COPY package.json pnpm-lock.yaml* ./

RUN pnpm install --frozen-lockfile || pnpm install

COPY . .

EXPOSE 3000

ENV HOSTNAME="0.0.0.0"

CMD ["pnpm", "dev"]
